### ISSUE TITLE
Warning with R4.0.1

### ISSUE THREAD

**Issue by StuartWheater** [obiba/opal-rserver#8]
When installing with R4.0.1, I get the following messages, is this significant?

```
Warning message:
package ‘opal’ is not available (for R version 4.0.1) 
Warning message:
package ‘opaladdons’ is not available (for R version 4.0.1) 
```

Could this be cause of "resourcer" package not being installed?

Stuart

**Comment by ymarcon** [comment]
It's because these R packages are no more in the cran.obiba.org, deprecated by opalr. Thanks for the report, I will update this meta-package.
